### ISSUE TITLE
Is it possible to have a CPU-only version for this?

### ISSUE THREAD

**Issue by AbhayKoushik** [YadiraF/DECA#27]
Hi @YadiraF, I got the following 
`AssertionError: Torch not compiled with CUDA enabled`

Pasting the traceback for your reference:

> Traceback (most recent call last):
>   File "demos/demo_reconstruct.py", line 103, in <module>
>     main(parser.parse_args())
>   File "demos/demo_reconstruct.py", line 36, in main
>     testdata = datasets.TestData(args.inputpath, iscrop=args.iscrop, face_detector=args.detector)
>   File "...DECA/decalib/datasets/datasets.py", line 70, in __init__
>     self.face_detector = detectors.FAN()
>   File ".../DECA/decalib/datasets/detectors.py", line 22, in __init__
>     self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
>   File ".../lib/python3.7/site-packages/face_alignment/api.py", line 75, in __init__
>     self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
>   File ".../lib/python3.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 30, in __init__
>     self.face_detector.to(device)
>   File ".../lib/python3.7/site-packages/torch/nn/modules/module.py", line 612, in to
>     return self._apply(convert)
>   File ".../lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
>     module._apply(fn)
>   File ".../lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
>     param_applied = fn(param)
>   File ".../lib/python3.7/site-packages/torch/nn/modules/module.py", line 610, in convert
>     return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
>   File ".../lib/python3.7/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled

Would love to have your answer soon, thanks!

**Comment by SNOWWHITE-STAR** [comment]
I am using MAC and encounter the same problem "Torch not compiled with CUDA enabled". As far as I know, pytorch3d can work on CPU with pytorch=1.7.1 only. Does this version of pytorch make the error?

**Comment by kaylolittlejohn** [comment]
same here

**Comment by kaylolittlejohn** [comment]
@SNOWWHITE-STAR inserted `device='cpu'` in the `face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)` and in `def __init__(self, config=None, device='cpu')` in deca.py and changed model load map location to cpu and these should work. on mac, had to add `os.environ['KMP_DUPLICATE_LIB_OK']='True'` for some reason.

**Comment by AbhayKoushik** [comment]
Thanks Kaylo! @kaylolittlejohn

**Comment by kaylolittlejohn** [comment]
no problem, to be honest i ran everything remote on linux gpu in the end. It was much easier that way for computational cost reasons. Had some concerns about running remotely but since their is no mesh renderer it works like a charm.

**Comment by zw20045500** [comment]
> @SNOWWHITE-STAR inserted `device='cpu'` in the `face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)` and in `def __init__(self, config=None, device='cpu')` in deca.py and changed model load map location to cpu and these should work. on mac, had to add `os.environ['KMP_DUPLICATE_LIB_OK']='True'` for some reason.

----hello, you test it's ok in Mac?  I modify self.model = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device='cpu') in detectors.py and `def __init__(self, config=None, device='cpu')` in deca.py.  And config.py and full_config.ymal. but it also raise AssertionError("Torch not compiled with CUDA enabled")

**Comment by yusufdeepwork** [comment]
Same issue with @zw20045500 . I tried the above solutions but It doesn't still work
