### ISSUE TITLE
CUDA Version issue

### ISSUE THREAD

**Issue by cedro3** [YadiraF/DECA#7]
I'm trying to run demo on Google Colab, but I get the following error:

AssertionError:
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

However, when I check the version with Nvidia-smi, it is CUDA version: 10.1, which is fine.
Is there any solution?

**Comment by RohithPillai** [comment]
Had the same issue. But reinstalling pytorch with cudatoolkit=10.1 fixed it for me.
`conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch`

**Comment by cedro3** [comment]
Thank you for the useful information. I'm running on Google Colab, so running the code below first solved the problem.

!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

Thank you. This problem has been resolved.

**Comment by cedro3** [comment]
Thank you for the useful information. I'm running on Google Colab, so running the code below first.

!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html <https://download.pytorch.org/whl/torch_stable.html>
Thank you. This issue has been resolved.

**Comment by cedro3** [comment]
This issue has been resolved.
